<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="tyuiu.cources.programming.interfaces">
      <HintPath>..\..\..\..\tyuiu.cources.programming.interfaces-b71f10fe05b408f7bda1aaffd8bcef4d9072f00e\tyuiu.cources.programming.interfaces.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
